import {
  Body,
  Container,
  Head,
  Html,
  Preview,
  Section,
  Text,
  Link,
  Hr,
} from '@react-email/components';
import * as React from 'react';

/**
 * Brand logo recreated in HTML to mirror /public/logo.svg.
 *
 * Why not embed the actual SVG (or a PNG copy)?
 *   - Gmail web strips `<svg>` elements out of the body.
 *   - Hosted PNG via `<img>` triggers the image-blocking placeholder in
 *     Gmail / Outlook until the recipient clicks "show images".
 *   - The logo is just two pieces of styled text, so we get pixel-near
 *     fidelity by rendering it as styled HTML — and it always shows up.
 *
 * Designers: if the brand mark stops being pure text (e.g. adds a glyph or
 * shape), revisit this and switch to a hosted PNG with the appropriate
 * `alt` text + width/height attributes.
 */
export function BrandLogo({ size = 32 }: { size?: number }) {
  return (
    <Link href="https://heylola.co" style={{ textDecoration: 'none' }}>
      <Text
        style={{
          fontFamily:
            'Inter, ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
          fontWeight: 900,
          fontStyle: 'italic',
          fontSize: size,
          letterSpacing: '-0.04em',
          lineHeight: 1,
          margin: 0,
        }}
      >
        <span style={{ color: '#0A0A0A' }}>Hey</span>
        <span style={{ color: '#F28C33' }}>Lola.</span>
      </Text>
    </Link>
  );
}

export interface LayoutProps {
  preview: string;
  children: React.ReactNode;
  /** Accent flavour — affects the small top stripe. */
  accent?: 'charcoal' | 'orange' | 'cream';
}

/**
 * Brand-aware shell used by every Hey Lola email.
 *
 * - 560px container, system font stack, charcoal text on bone background.
 * - Always renders a `<Preview>` (the snippet email clients show before opening).
 * - Footer includes the reply-to inbox so users have a hook back to support.
 *
 * Designers / copywriters: do NOT edit this file directly. Tweak per-template
 * copy in `emails/<template>.tsx`. Brand changes (colours, footer text) belong
 * here so they propagate to every email.
 */
export function Layout({ preview, children, accent = 'charcoal' }: LayoutProps) {
  const stripe = accent === 'orange' ? '#C4622D' : accent === 'cream' ? '#FDF6EE' : '#0A0A0A';
  return (
    <Html>
      <Head />
      <Preview>{preview}</Preview>
      <Body style={body}>
        <Container style={container}>
          <Section style={{ ...stripeStyle, backgroundColor: stripe }} />
          <Section style={brandRow}>
            <BrandLogo size={32} />
            <Text style={brandTagline}>The boutique pet club</Text>
          </Section>

          <Section>{children}</Section>

          <Hr style={hr} />
          <Section>
            <Text style={footerText}>
              Hey Lola · <Link href="mailto:hey@heylola.co" style={{ color: '#888', textDecoration: 'underline' }}>hey@heylola.co</Link>
            </Text>
            <Text style={footerSmall}>
              You're receiving this because you submitted a form on heylola.co.
              Reply to this email to unsubscribe or contact our team directly.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

// ────────── styles ──────────

const body: React.CSSProperties = {
  backgroundColor: '#F7F5F2',
  margin: 0,
  padding: '24px 0',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  color: '#1a1a1a',
};

const container: React.CSSProperties = {
  backgroundColor: '#FFFFFF',
  maxWidth: 560,
  margin: '0 auto',
  borderRadius: 16,
  overflow: 'hidden',
  padding: '0',
};

const stripeStyle: React.CSSProperties = {
  height: 4,
  width: '100%',
};

const brandRow: React.CSSProperties = {
  padding: '24px 32px 12px',
};

const brandTagline: React.CSSProperties = {
  fontSize: 11,
  fontStyle: 'italic',
  color: '#888',
  margin: '6px 0 0',
  letterSpacing: '0.05em',
};

const hr: React.CSSProperties = {
  borderColor: '#EEE',
  margin: '32px 32px 16px',
};

const footerText: React.CSSProperties = {
  fontSize: 12,
  color: '#888',
  textAlign: 'center',
  margin: '0 32px 4px',
};

const footerSmall: React.CSSProperties = {
  fontSize: 10,
  color: '#AAA',
  textAlign: 'center',
  margin: '0 32px 16px',
  lineHeight: 1.5,
};

// ────────── shared sub-components for templates ──────────

export const Section32: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Section style={{ padding: '0 32px' }}>{children}</Section>
);

export const Heading1: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={{ fontSize: 24, fontWeight: 700, letterSpacing: '-0.02em', margin: '16px 0 16px', lineHeight: 1.2 }}>
    {children}
  </Text>
);

export const Heading2: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={{ fontSize: 18, fontWeight: 700, margin: '16px 0 12px', lineHeight: 1.3 }}>
    {children}
  </Text>
);

export const Body14: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={{ fontSize: 14, lineHeight: 1.6, margin: '0 0 14px', color: '#1a1a1a' }}>
    {children}
  </Text>
);

export const Muted12: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={{ fontSize: 12, color: '#888', margin: '0 0 8px' }}>
    {children}
  </Text>
);

export const CtaButton: React.FC<{ href: string; children: React.ReactNode; color?: 'charcoal' | 'orange' }> = ({ href, children, color = 'charcoal' }) => (
  <Section style={{ textAlign: 'center', margin: '24px 0' }}>
    <Link
      href={href}
      style={{
        display: 'inline-block',
        padding: '14px 28px',
        backgroundColor: color === 'orange' ? '#C4622D' : '#0A0A0A',
        color: '#FFFFFF',
        textDecoration: 'none',
        borderRadius: 999,
        fontWeight: 700,
        fontSize: 12,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
      }}
    >
      {children}
    </Link>
  </Section>
);

export interface KeyValueProps {
  rows: Array<[string, React.ReactNode]>;
}

export const KeyValueTable: React.FC<KeyValueProps> = ({ rows }) => (
  <Section style={{ padding: '0 32px' }}>
    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
      <tbody>
        {rows.map(([k, v], i) => (
          <tr key={i}>
            <td style={{ padding: '6px 12px 6px 0', color: '#888', width: 130, verticalAlign: 'top' }}>
              {k}
            </td>
            <td style={{ padding: '6px 0', verticalAlign: 'top' }}>{v}</td>
          </tr>
        ))}
      </tbody>
    </table>
  </Section>
);

export const Quote: React.FC<{ children: React.ReactNode; tint?: 'cream' | 'stone' }> = ({ children, tint = 'stone' }) => (
  <Section
    style={{
      backgroundColor: tint === 'cream' ? '#FDF6EE' : '#F7F5F2',
      padding: '14px 18px',
      borderRadius: 10,
      margin: '12px 32px',
    }}
  >
    <Text style={{ fontSize: 14, color: tint === 'cream' ? '#6B4421' : '#444', margin: 0, fontStyle: 'italic', lineHeight: 1.5 }}>
      {children}
    </Text>
  </Section>
);
