// Seed the Foundation `shelters` collection in Firestore with the 5 NYC
// rescue partners + their adoptable dogs (real profiles). The /foundation
// page reads this collection live — nothing is hardcoded in the app.
//
//   FIREBASE_ADMIN_PROJECT_ID=...    \
//   FIREBASE_ADMIN_CLIENT_EMAIL=...  \
//   FIREBASE_ADMIN_PRIVATE_KEY="..." \
//   FIREBASE_DATABASE_ID=ai-studio-041ff40c-7f72-4aad-a12c-bcd060760a1d \
//   node scripts/import_shelters.mjs
//
// Idempotent: each shelter is a doc keyed by id and written with merge, so
// re-running refreshes the data. Edit the SHELTERS array (or the Firestore
// docs directly) to add/update real dogs as Hey Lola onboards them.
import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';

// Base URL used to build the shareable shelter edit links.
const BASE = (process.env.APP_URL || 'https://heylola.co').replace(/\/$/, '');

const env = (k) => process.env[k] || '';
const databaseId = env('FIREBASE_DATABASE_ID');

// Robust private-key parser: tolerates surrounding quotes, literal "\n",
// real newlines, CRLF and base64-encoded PEM. Mirrors api/_admin.ts so the
// script never trips on how PowerShell/bash store the multi-line key.
function parsePrivateKey(raw) {
  let key = raw;
  if (key.charCodeAt(0) === 0xFEFF) key = key.slice(1);
  key = key.trim();
  if ((key.startsWith('"') && key.endsWith('"')) || (key.startsWith("'") && key.endsWith("'"))) key = key.slice(1, -1);
  if (!key.startsWith('-----BEGIN')) {
    const stripped = key.replace(/\s/g, '');
    if (/^[A-Za-z0-9+/=]+$/.test(stripped) && stripped.length > 1000) {
      try { const decoded = Buffer.from(stripped, 'base64').toString('utf8'); if (decoded.includes('-----BEGIN')) key = decoded; } catch { /* ignore */ }
    }
  }
  if (key.includes('\\n')) key = key.replace(/\\n/g, '\n');
  return key.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
}

// EASIEST path: point GOOGLE_APPLICATION_CREDENTIALS (or SERVICE_ACCOUNT_FILE)
// at your downloaded service-account JSON file — no key copy-pasting at all.
// Fallback: the three FIREBASE_ADMIN_* env vars (key parsed robustly above).
const keyFile = env('GOOGLE_APPLICATION_CREDENTIALS') || env('SERVICE_ACCOUNT_FILE');
let credential;
if (keyFile) {
  const sa = JSON.parse(readFileSync(keyFile, 'utf8'));
  credential = cert({ projectId: sa.project_id, clientEmail: sa.client_email, privateKey: sa.private_key });
} else {
  const projectId = env('FIREBASE_ADMIN_PROJECT_ID');
  const clientEmail = env('FIREBASE_ADMIN_CLIENT_EMAIL');
  const pemFromEnv = env('FIREBASE_ADMIN_PRIVATE_KEY');
  if (!projectId || !clientEmail || !pemFromEnv) {
    console.error('Set GOOGLE_APPLICATION_CREDENTIALS to your service-account JSON file path, OR set FIREBASE_ADMIN_PROJECT_ID / FIREBASE_ADMIN_CLIENT_EMAIL / FIREBASE_ADMIN_PRIVATE_KEY.');
    process.exit(1);
  }
  credential = cert({ projectId, clientEmail, privateKey: parsePrivateKey(pemFromEnv) });
}

const app = initializeApp({ credential });
const db = databaseId ? getFirestore(app, databaseId) : getFirestore(app);

// Source of truth mirrors src/data/sheltersSeed.ts (real dogs scraped from each
// partner's site). Keep both in sync. Badass + Social Tees list dogs through
// external platforms, so their dogs are added manually from /admin → Shelters.
const SHELTERS = [
  {
    id: 'bobbi-and-the-strays', order: 1,
    name: 'Bobbi and the Strays',
    city: 'Queens & Long Island, NY', region: 'Americas',
    blurb: 'A no-kill organization rescuing and rehabilitating orphaned, stray, abused and special-needs cats and dogs across New York City and Long Island.',
    website: 'https://bobbiandthestrays.org/adopt-a-dog/',
    dogs: [
      { id: 'bobbi-abby', name: 'Abby', breed: 'Mixed breed', age: 'Adult', sex: 'Female', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2025/02/482358688_122216509544229903_3555225045807675956_n-768x1024.jpg', bio: 'This beautiful girl has not had an easy life. Abby is ready for a family who will give her the love she deserves.' },
      { id: 'bobbi-athena', name: 'Athena', breed: 'Pit Bull Terrier mix', age: '7 yrs', sex: 'Female', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2022/12/385907442_10231561518047156_2954351285001090201_n.jpg', bio: 'Athena has overcome unthinkable hardships and is ready for a loving forever home.' },
      { id: 'bobbi-biscuit', name: 'Biscuit', breed: 'Mixed breed', age: 'Senior', sex: 'Female', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2026/04/669885288_10230870437004967_2817426302205603059_n-790x1024.jpg', bio: 'Brave little Biscuit is ready to begin her new golden chapter in a home where she will be loved.' },
      { id: 'bobbi-bravo', name: 'Bravo', breed: 'Mixed breed', age: 'Senior', sex: 'Male', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2026/02/658157127_26476333505327016_5896507743526475596_n-682x1024.jpg', bio: 'A gentle, loving senior with some vision impairment, looking for a calm, caring home.' },
      { id: 'bobbi-buckey', name: 'Buckey', breed: 'Mixed breed', age: '1 yr', sex: 'Male', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2025/09/549511460_24722282740732110_7967736384481264689_n-768x1024.jpg', bio: 'A one-year-old bundle of love ready to be your future best friend.' },
      { id: 'bobbi-candy', name: 'Candy', breed: 'Mixed breed', age: 'Adult', sex: 'Female', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2026/04/680749532_10231012781563492_742745350360228881_n-1024x716.jpg', bio: 'Our delicious and sweet Candy is ready to begin her new life in a loving home.' },
      { id: 'bobbi-clover', name: 'Clover (Buddy)', breed: 'Cocker Spaniel / Shih Tzu mix', age: '8.5 yrs', sex: 'Male', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2019/09/338192929_1550562875436084_5886594316250828194_n.jpg', bio: 'A gorgeous senior who needs a new forever home full of comfort and love.' },
      { id: 'bobbi-griselda', name: 'Griselda', breed: 'Mixed breed', age: 'Adult', sex: 'Female', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2024/02/476358253_9306545306065770_3539563277779394879_n-767x1024.jpg', bio: 'A very friendly, loving and super sweet best friend waiting just for you.' },
      { id: 'bobbi-gucci', name: 'Gucci', breed: 'Mixed breed', age: 'Adult', sex: 'Male', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2025/02/648870855_26274067995553569_5785104265734854406_n-768x1024.jpg', bio: 'Handsome Gucci was abandoned in the cold and is now searching for a family to trust again.' },
      { id: 'bobbi-henry', name: 'Henry', breed: 'Mixed breed', age: 'Adult', sex: 'Male', photo: 'https://bobbiandthestrays.org/wp-content/uploads/2026/01/624254530_3014599682080917_5603843912712303186_n.jpg', bio: 'Henry lost his special person and is now in search of a loving new home.' },
    ],
  },
  {
    id: 'badass-animal-rescue', order: 2,
    name: 'Badass Animal Rescue',
    city: 'Brooklyn, NY', region: 'Americas',
    blurb: 'A foster-based 501(c)3 saving and rehabilitating loving dogs from high-kill shelters since 2011 — over 4,000 dogs rescued.',
    website: 'https://badassanimalrescue.com/find-a-dog-new',
    dogs: [
      { id: 'badass-amy-madigan', name: 'Amy Madigan', breed: 'Mixed breed', age: '10 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/280707be-db7d-4131-b96d-8e14ea70d08f/Amy+Madigan+-+Adoption+Event+-+Clare+Lockhart+4.png?format=500w', bio: 'Okay, so I may not have many teeth, but I\'ve got smiles for days — especially when dinner\'s coming or my favorite person walks through the door. I\'m a low-key, big-hearted homebody who takes a little time to warm up, but once I do? I\'m your shadow. Your lap warmer.' },
      { id: 'badass-bob-dylan', name: 'Bob Dylan', breed: 'Mixed breed', age: '4 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/3c9a0133-041f-45a2-ab43-dcbf32e13f3f/BobDylan.jpg?format=500w', bio: 'Looking to bring home a gentle giant with a heart of gold? Don’t think twice! I love spending my time cuddling and relaxing with my people, or hanging out with other pups. I have a gentle and dainty play style, and can sometimes be a little shy.' },
      { id: 'badass-boom', name: 'Boom', breed: 'Mixed breed', age: '6 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/43b1e18c-ed75-47ae-96a7-579133e4be85/IMG_5713.JPG?format=500w', bio: 'How ‘bout them Dawgs! Hi, I’m Boom—a calm, steady senior pup with soft energy and a big heart ready for a home of my own. Like my namesake from UGA football lore, I don’t sprint out of the gate—but once I warm up, I’m the quiet MVP of cuddles, couch time, and peaceful walks.' },
      { id: 'badass-boots', name: 'Boots', breed: 'Mixed breed', age: '2 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/83347cd5-32c3-44ac-a105-e76725317b3e/Boots.jpg?format=500w', bio: 'This Boots was made for walkin\'... to the park, that is! If you’re looking for a fun, silly vibe, then I’m your guy. I love playing outside and—no surprises here—going for long walks.' },
      { id: 'badass-carla-espinosa', name: 'Carla Espinosa', breed: 'Mixed breed', age: '3 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/661e7d4c-3a1d-4457-81a9-d85a1124fc3f/IMG_9099.jpg?format=500w', bio: 'Walks? Absolutely my thing — I will explore every corner of this city with a grin on my face and a nose to the ground. But don\'t let the adventure fool you: the moment we get home, I\'m climbing into the nearest lap like it\'s my full-time job.' },
      { id: 'badass-cleopatra', name: 'Cleopatra', breed: 'Mixed breed', age: '4 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/f5615a1b-0d64-4902-acda-e65bbae51f9e/Cleopatra+-+Shelter+8.png?format=500w', bio: 'Don\'t let the composed exterior fool you — I\'ve got layers. Sure, I\'m the calm one in the room, the one who takes her time before asking for your attention attention. But get on my good side and I\'m a full-time cuddle companion who will boop your hand until you pet me again.' },
      { id: 'badass-eddie-kendricks', name: 'Eddie Kendricks', breed: 'Mixed breed', age: '6 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/1417b830-5019-4a47-bc9d-77478acf7839/1000042553.png?format=500w', bio: 'If you live a quieter life, love the outdoors, and believe that senior dogs deserve second chances, I might just be the one you’ve been waiting for! I’m a senior boy with a big heart and a touch of anxiety. In loud, busy environments, I sometimes struggle.' },
      { id: 'badass-flaco', name: 'Flaco', breed: 'Mixed breed', age: '1 yr', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/364cb9de-a97a-40c2-b698-0222d56b1de9/Flaco+-+Adoption+Event+-+Gigi+Schweitzer+6+%281%29.jpg?format=500w', bio: 'I escaped a life that didn\'t quite fit and landed somewhere much better — sound familiar? Every walk is a full investigation, every new smell a breaking story, and every snuggle session a well-earned reward. I\'m a little clumsy, a lot curious, and genuinely up for anything.' },
      { id: 'badass-freret', name: 'Freret', breed: 'Mixed breed', age: '2 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/a8f47f00-a078-4aeb-b548-a99eddc47975/Fretet+-+Shelter+8.png?format=500w', bio: 'Exploring is kind of my thing. New smells, new streets, new people to charm — I\'m here for all of it. I\'m gentle, I\'m friendly, and I have a signature move that involves putting my paws on your shoulders and making you feel like the most important person in the room.' },
      { id: 'badass-golden', name: 'Golden', breed: 'Mixed breed', age: '7 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/8905ba07-5d93-4753-8660-8022b316546b/Golden+-+Adoption+Event+-+Gigi+Schweitzer+6+%282%29.jpg?format=500w', bio: 'Rolling around on the floor, winning over strangers with a single soulful look, chasing a scent that only I can smell — that\'s basically my whole vibe. I\'m goofy in the best way, and I warm up fast once I\'ve locked eyes with you (fair warning: the eye contact gets intense).' },
      { id: 'badass-iris', name: 'Iris', breed: 'Mixed breed', age: '9 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/340fc935-c7d9-480a-acfb-4b66498b8ff4/Iris+-+Shelter+8.JPG?format=500w', bio: 'Wandered into this world like a goddess with somewhere better to be — and turns out, that place is Brooklyn. I\'m a low-key, affectionate soul who\'s most at home sprawled on a dog bed surrounded by people who don\'t mind when I nudge their hand for more pets.' },
      { id: 'badass-jane-goodall', name: 'Jane Goodall', breed: 'Mixed breed', age: '9 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/f4749095-e48c-403c-9cf8-9ae05ba1e808/dogs+with+badges+-+Jane+Goodall.png?format=500w', bio: 'I’m a gentle, low-key soul who believes the best adventures happen from a cozy couch. I win people over quietly — with soft eyes, a calm presence, and a well-timed head resting in your lap. I adore companionship and thrive in peaceful spaces where love is steady and unhurried.' },
      { id: 'badass-janitor', name: 'Janitor', breed: 'Mixed breed', age: '6 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/873e5176-ba26-4f7c-888e-3accd8cef6a3/694330592_10164991912032241_5201790143844900753_n+%282%29.jpg?format=500w', bio: 'Check back for more information about Janitor soon!' },
      { id: 'badass-jd', name: 'JD', breed: 'Mixed breed', age: '3 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/21246c42-1087-4336-94b8-716468517f17/IMG_7438+%281%29.jpg?format=500w', bio: 'The second I meet someone, I\'m in. No awkward getting-to-know-you phase, no slow warm-up — I just decided we\'re friends now, and that\'s that. I\'m the kind of guy who knows how to exist in a home like I\'ve always lived there. Walkies? Obsessed. Cuddles after? Obviously.' },
      { id: 'badass-jonquel-jones', name: 'Jonquel Jones', breed: 'Mixed breed', age: '5 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/d65b5d4a-3520-472d-886c-fd1f3813c285/Jonquel+Jones+-+Shelter+8.JPG?format=500w', bio: 'My people say I\'m a team player, and honestly? Guilty. I\'m at my best when there\'s someone to cuddle with, a dog to wrestle in the morning, and a lap to pass out in by evening. I\'ll greet you like you just won a championship — jumping up, asking for pets (it\'s cute, I promise).' },
      { id: 'badass-justine-biagi', name: 'Justine Biagi', breed: 'Mixed breed', age: '9 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/87818d3f-181b-4f6e-9235-286fc958f29f/Justine+Biagi+-+NYC+Foster+35.jpeg?format=500w', bio: 'Once I decide a place is mine, I tend to settle in pretty quickly — grab a toy, find a cozy spot, let\'s hang. I like to take a beat with new people before I go full goofball, but it doesn\'t take long.' },
      { id: 'badass-kyra-milligan', name: 'Kyra Milligan', breed: 'Mixed breed', age: '5 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/09c48a1b-81e6-4da7-adc7-4400d4818b7c/Kyra+Milligan+-+Adoption+Event+-+Gigi+1.jpg?format=500w', bio: 'Kyra is currently staying with our boarding partner outside the city. Check back for more information about her soon!' },
      { id: 'badass-nikola-jokic', name: 'Nikola Jokic', breed: 'Mixed breed', age: '3 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/9b946b79-fd54-43a5-8259-d9ae339c60de/Nikola+Jokic+-+Shelter+5.png?format=500w', bio: 'Napping on the hardwood in the middle of the room? That\'s my move. I\'m the guy who makes the neighbors stop mid-construction to say something nice, who walks at your pace and leans against your legs when we sit outside.' },
      { id: 'badass-perry-cox', name: 'Perry Cox', breed: 'Mixed breed', age: '5 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/08734c4a-9e57-4cbc-8e01-1065fe96b2aa/image+%282%29.png?format=500w', bio: 'Snuggling? My cardio. Napping with my tongue out? My sport. Being wherever my people are? My whole personality. I\'m goofy, I\'m gentle, and I take couch real estate very seriously. I get along with dogs, I\'m cool with cats, and once I\'m comfortable somewhere, I am all in.' },
      { id: 'badass-saja', name: 'Saja', breed: 'Mixed breed', age: '5 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/edf123dc-74b5-429f-b91c-bb2122a452b6/Saja+-+Adoption+Event+-+Gigi+7.jpg?format=500w', bio: 'They call my namesake a demon hiding behind a pretty face and a flawless stage presence. I\'m not here to confirm or deny anything — I\'ll just say I came all the way from Georgia, passed my cat test without a scene, charmed every dog I\'ve met, and learned "sit" in a day.' },
      { id: 'badass-shawn-johnson', name: 'Shawn Johnson', breed: 'Mixed breed', age: '6 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/c5b06f0e-b1a6-47f9-b364-a44fda7b0b50/Shawn+Johnson+-+Shelter+5.JPG?format=500w', bio: 'They don’t call me Shawn Johnson for nothing. I may be petite, but I stick the landing every single time… especially when it’s into your lap. I’ve mastered the balance beam of couch life—calm, graceful, and gold-medal at cuddling—and I greet new people like it’s the Olympic final…' },
      { id: 'badass-sunbeam', name: 'Sunbeam', breed: 'Mixed breed', age: '5 yrs', sex: 'Female', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/e551f25a-955f-4c43-bf61-18a05d53aefe/dogs+with+badges+-+Sunbeam.png?format=500w', bio: 'You’ll totally get my name when you meet me: I really am as bright and friendly as a sunbeam! I’m sweet as can be and love meeting new people. My happy place is outside, whether I’m exploring, going for a long walk, or taking in all the yummy smells of the outdoors.' },
      { id: 'badass-treasure-chest', name: 'Treasure Chest', breed: 'Mixed breed', age: '3 yrs', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/a8a17c45-d250-41cb-ad4a-70e1ae2d91dd/TreasureChest.jpg?format=500w', bio: 'I’m very aptly named—I really am a treasure! I’m a very silly and active guy who just wants to spend hours playing with my people. Now I just need to find the perfect forever family to head to the park with!' },
      { id: 'badass-tucks', name: 'Tucks', breed: 'Mixed breed', age: '1 yr', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/84dd05d2-b4da-40be-910b-f6f04aa457a7/Tucks+-+Shelter+10.png?format=500w', bio: 'I didn\'t come with beads or a float, but I showed up ready to have a good time. I bond fast, I love a crowd, and I\'ll find my way onto your couch before you even finish introductions. I\'ve got energy when it counts and calm when it matters.' },
      { id: 'badass-turk', name: 'Turk', breed: 'Mixed breed', age: '1 yr', sex: 'Male', photo: 'https://images.squarespace-cdn.com/content/v1/5fa9da29ae329e7a2eb6cbcc/fe4e49b3-5fa9-4edc-9078-76b785fb3fe2/image_%288%29+%281%29.png?format=500w', bio: 'Check back for more information about Turk soon!' },
    ],
  },
  {
    id: 'ama-animal-rescue', order: 3,
    name: 'AMA Animal Rescue',
    city: 'Brooklyn, NY', region: 'Americas',
    blurb: 'Angels for Mistreated Animals — a no-kill rescue in Brooklyn rehabilitating abused and injured dogs and cats and giving them loving futures.',
    website: 'https://amaanimalrescue.org/pet-type/dogs/',
    dogs: [
      { id: 'ama-penny', name: 'Penny', breed: 'Terrier Mix', age: '1 yr', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/820c5d53-c65b-4245-94e6-92e6c9f65fa6-scaled-e1779281562667-250x250.jpeg', bio: 'Meet Penny, the most sweet and gentle girl. Penny was found at a nearby park all alone, and the person who found Penny said they looked all over for her owner.' },
      { id: 'ama-isaiah', name: 'Isaiah', breed: 'Maltese Mix', age: '14 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/540aa232-2983-4ca6-bf0d-7058a1d7aa94-scaled-250x250.jpg', bio: 'Meet Isaiah, a sweet and friendly senior boy looking for a loving home to spend his golden years. Isaiah may be blind, but that doesn’t stop him from enjoying life to the fullest.' },
      { id: 'ama-theodore', name: 'Theodore', breed: 'Beagle', age: '1 yr', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/69cb0472-709a-4676-8129-41b6e7327b66-scaled-250x250.jpg', bio: 'Meet Theodore, a beagle whose life is finally beginning after being rescued from Ridglan Farms, a large breeding and research facility in Wisconsin. For most of his life, Theodore knew only the inside of a cage.' },
      { id: 'ama-simon', name: 'Simon', breed: 'Beagle', age: '1 yr', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/IMG_5181-scaled-250x250.jpeg', bio: 'Introducing Simon, a beagle rescued from Ridglan Farms, where he was bred and used for biomedical research. Simon spent his days in a facility with no fresh air, daylight, or outdoor time.' },
      { id: 'ama-alvin', name: 'Alvin', breed: 'Beagle', age: '2 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/8b7e5a9e-483a-4197-badc-070f17ec04f6-scaled-250x250.jpg', bio: 'Introducing Alvin. Alvin’s story begins at Ridglan Farms, a breeding facility in Wisconsin where he was kept for biomedical research.' },
      { id: 'ama-cookie', name: 'Cookie', breed: 'French Bulldog', age: '3 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/4d9ceaed-4526-48be-9b7a-994bf30c0eb0-scaled-250x250.jpeg', bio: 'Cookie is the kind of dog who makes people stop mid-sentence just to say, “Oh my gosh, look at her.” With her squishy little face and irresistible charm, she turns heads everywhere she goes.' },
      { id: 'ama-bella', name: 'Bella', breed: 'Maltese Mix', age: '13 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-10-at-4.43.00-PM-250x250.jpeg', bio: 'Meet Bella — a gentle, affectionate pup searching for a warm and patient home. She is part a deeply bonded pair with Chanel.' },
      { id: 'ama-chanel', name: 'Chanel', breed: 'Poodle', age: '15 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-10-at-4.43.00-PM-3-250x250.jpeg', bio: 'Meet Chanel, a sweet, devoted poodle who is looking for a loving home to spend her golden years. She is part of a deeply bonded pair with Bella. Chanel is the quiet guardian of her little family.' },
      { id: 'ama-olive', name: 'Olive', breed: 'Pit Bull Mix', age: '1 yr', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/04/6d1918c2-d803-40e0-8429-40740e1b4a41-250x250.jpg', bio: 'Meet Olive, a truly unforgettable pup with a big personality packed into one very special dog. With just one eye, Olive has a look that turns heads everywhere she goes, but it is her personality that really makes her shi…' },
      { id: 'ama-muneco', name: 'Muñeco', breed: 'Mixed Breed', age: '11 mo', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/341b36dd-eb08-44f5-8ca5-cae29ad121f1-scaled-250x250.jpg', bio: 'Meet Muñeco, a truly special little soul. His name means “little doll,” and it fits him perfectly, he’s as sweet and endearing as they come.' },
      { id: 'ama-maya', name: 'Maya', breed: 'Pit Bull Mix', age: '2 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/3057ea85-6d9f-4318-98f5-8cd7464e6bdf-scaled-250x250.jpg', bio: 'Meet Maya ! Maya is a social butterfly with a heart full of love and a tail that never stops wagging. She’s dog-friendly and absolutely lights up when she gets to meet new people and make new canine friends.' },
      { id: 'ama-poppy', name: 'Poppy', breed: 'Brussels Griffon Mix', age: '4 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/46e2eb34-2da8-4eae-9ba8-9bd6075e0a95-250x250.jpg', bio: 'Meet Poppy! Poppy’s journey hasn’t been an easy one. She was found wandering the streets, very matted and frightened, clearly having been through more than any dog should.' },
      { id: 'ama-cj', name: 'CJ', breed: 'Terrier Mix', age: '1 yr', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/8dfca55d-700a-4a25-b93f-0376ea10edea-250x250.jpg', bio: 'Meet CJ, a gentle, sweet soul who is looking for a calm, quiet home where he can feel safe and secure. Loud noises can be scary for him right now, so he would do best in a peaceful environment with patient people who und…' },
      { id: 'ama-mable', name: 'Mable', breed: 'Hound Mix', age: '9 mo', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/997daccd-4d0e-4882-b488-e4bc871a1259-scaled-250x250.jpg', bio: 'Introducing sweet Mable! Mable is a bright, happy puppy with an outgoing personality and a whole lot of love to give. She is energetic, playful, and ready to make new friends wherever she goes.' },
      { id: 'ama-bruno', name: 'Bruno', breed: 'Chihuahua Mix', age: '5 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/11a8f6d5-aa51-41df-b90a-e42a69f094c9-250x250.jpg', bio: 'Introducing Bruno! Bruno is a sweet little soul who has been through a lot. He was lovingly surrendered after his family lost their home in a tragic fire and, understandably, could no longer care for him, mentally or phy…' },
      { id: 'ama-russell', name: 'Russell', breed: 'Chihuahua Mix', age: '1 yr', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/6c70be48-ccf0-45a3-8d60-32fd03d1f737-scaled-250x250.jpg', bio: 'Meet Russell, a silly little guy with a wiggly butt and a whole lot of love to give! Russell is a Chihuahua mix bursting with personality and energy.' },
      { id: 'ama-jasper', name: 'Jasper', breed: 'Pit Bull Mix', age: '5 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/01/4fc70c5d-e70a-4997-8552-330c32683b9f-scaled-250x250.jpg', bio: 'Introducing Jasper, a joyful boy who’s ready to be your adventure buddy! Jasper is a large, energetic dog who absolutely loves people. He’s friendly, social, and happy to make new human friends wherever he goes.' },
      { id: 'ama-isis', name: 'Isis', breed: 'Rottweiler/Bully Mix', age: '4 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/a399bc24-86ee-4918-9e2a-929fcaf9442d-250x250.jpg', bio: 'Meet Isis, a big hearted girl with an even bigger head to pet :) Isis is a Rottweiler/Bully mix who is definitely large in size, but she’s even larger in love.' },
      { id: 'ama-cookie-bulldog', name: 'Cookie', breed: 'Bulldog', age: '2 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/9b869518-d4cf-41e5-b9d7-f76d587166f6-250x250.jpg', bio: 'Meet Cookie 🍪 Cookie came to us as a stray suffering from a severe, painful skin infection, and it was clear she’d had a rough start.' },
      { id: 'ama-apollo', name: 'Apollo', breed: 'Poodle', age: '3 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/10/f9f3279e-e553-4c55-a6d0-040b4fdc80ee-scaled-250x250.jpg', bio: 'Apollo’s name fits him perfectly - he’s got a heart that shines brighter than the sun, even after some dark days. This sweet poodle was abandoned by the family he trusted most, and despite people trying to reach them, no…' },
      { id: 'ama-santana', name: 'Santana', breed: 'Shih Tzu Mix', age: '16 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/10/d6757908-ecb6-4035-bd88-7aeb8ce6bb7a-scaled-250x250.jpg', bio: 'Meet Santana, the irresistibly adorable Shih Tzu mix who bears an uncanny resemblance to a certain lovable Wookiee from Star Wars, yes, we’re talking about Chewy!' },
      { id: 'ama-lilly', name: 'Lilly', breed: 'Yorkshire Terrier', age: '11 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/05/f544e698-773b-474c-a828-d7aecec4f15b-250x250.jpg', bio: 'Lilly is a small but mighty Yorkie with a heart full of love. This sweet girl was found alone on the street, bravely carrying a large mass on her belly.' },
      { id: 'ama-meeko', name: 'Meeko', breed: 'Chihuahua', age: '16 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/05/5bb23ab5-e548-455d-aa04-59aa97d31884-250x250.jpg', bio: 'Meet Meeko, a sweet senior looking for a second chance. After years of being confined to a small crate, with no medical care, no affection, and no understanding of what it means to be loved, Meeko is finally getting the…' },
      { id: 'ama-octavius', name: 'Octavius', breed: 'Pit Bull Mix', age: '1 yr', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/05/47233a1c-5a6e-4098-a0bb-c0fbef59df01-250x250.jpg', bio: 'This is little Octavius, a spunky little guy ready to find his forever family. Octavius was surrendered by his previous owner, with little history.' },
      { id: 'ama-wren', name: 'Wren', breed: 'Mixed Breed', age: '1 yr', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/04/7798fb0c-8ae4-4b85-ab88-bdc0bb800bf4-e1768517962350-250x250.jpg', bio: 'Introducing Wren! Wren is a bright, lively pup with a wonderful mix of curiosity, playfulness, and sweetness. She loves exploring her world, discovering new things, and letting you know exactly how she feels along the wa…' },
      { id: 'ama-gus', name: 'Gus', breed: 'Mixed Breed', age: '2 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/02/9dcda8a1-2bdc-4fd2-a582-e87f6a4cd6da-scaled-250x250.jpg', bio: 'Gus is a loving and resilient dog with a heart of gold, patiently waiting for a family to call his own. Found wandering the streets alone, Gus was thin, scared, and uncertain about the world around him.' },
      { id: 'ama-big-boy', name: 'Big Boy', breed: 'Mixed Breed', age: '9 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/03/a059ca87-ae0f-4745-b2f3-e5b906ec201b-250x250.jpg', bio: 'Meet Big Boy, a gentle soul with eyes that speak volumes. When we first saw him, there was a sadness in his gaze, one that spoke of his difficult past.' },
      { id: 'ama-rocky', name: 'Rocky', breed: 'Australian Shepherd/Rottweiler Mix', age: '7 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/02/293f56e2-8a49-4f16-818b-75c80f1c7065-1-250x250.jpg', bio: 'Meet Rocky, the ultimate lover boy with a heart as big as his paws! This Rottweiler/Australian Shepherd mix is a true charmer, always ready to shower you with affection and bask in all the love you can give.' },
      { id: 'ama-bambi', name: 'Bambi', breed: 'Mixed Breed', age: '1 yr', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2026/05/2edacfd3-4022-42b7-9e64-0aa124f5a418-scaled-250x250.jpg', bio: 'Meet Bambi, a sweet and loving girl in need of a fresh start after a rough beginning. At just 4 months old, Bambi was found abandoned at a precinct, visibly malnourished and scared.' },
      { id: 'ama-pooch', name: 'Pooch', breed: 'Cane Corso', age: '6 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2025/01/ffd7880e-766c-40fc-b1e5-556a18930abd-scaled-e1777759982133-250x250.jpeg', bio: 'Meet Pooch, the giant with a heart of gold and a face that’s pure mush! This lovable Cane Corso hails from an AKC champion bloodline, descending from generations of superb, Cane Corsos known for their strength, composure…' },
      { id: 'ama-esteban', name: 'Esteban', breed: 'Pit Mix', age: '3 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2024/10/esteban1-250x250.jpg', bio: 'Meet Esteban, your future best friend! Esteban is a true survivor. This brave boy was initially adopted from the ACC, but unfortunately faced a heartbreaking situation shortly after when he was hit by a car and left with…' },
      { id: 'ama-cheeks', name: 'Cheeks', breed: 'Chihuahua Mix', age: '5 yrs', sex: 'Female', photo: 'https://amaanimalrescue.org/wp-content/uploads/2024/06/945be44f-2b7c-4f8f-ade0-2c91da39ac55-e1744483040912-250x250.jpg', bio: 'Meet Cheeks! This sweet girl was pulled from the ACC with just hours before she was scheduled to be euthanized. Upon meeting her, she was timid, sick, and unsure what her future would look like.' },
      { id: 'ama-marshmallow', name: 'Marshmallow', breed: 'Pit Bull Mix', age: '3 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2024/01/f44c31bb-faab-46dc-9505-c0daf20949b9-e1720202364900-250x250.jpg', bio: '🚨 MARSHMALLOW HAS BEEN STOLEN🚨 We are currently pursuing legal action to locate and recover him. A reward of $8,000 is being offered for information leading to his safe return.' },
      { id: 'ama-mickey', name: 'Mickey', breed: 'Yorkie Mix', age: '16 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2023/07/47a54fb5-8f72-42f9-a0ce-5c493318bc27-250x250.jpg', bio: 'Need a bit of magic to spruce up your life? Mickey here is ready to make your dreams come true! His big ears aren’t as round as his mouse counterpart, and he barks rather than squeaks, but he’s got the same whimsical spi…' },
      { id: 'ama-rex', name: 'Rex', breed: 'Pit Mix', age: '7 yrs', sex: 'Male', photo: 'https://amaanimalrescue.org/wp-content/uploads/2022/01/IMG_3651-e1702416700441-250x250.jpg', bio: 'When we first laid eyes on Rex, it was heartbreaking to see the state he was in. His body was covered in bite marks and old scars that had already healed.' },
    ],
  },
  {
    id: 'social-tees', order: 4,
    name: 'Social Tees Animal Rescue',
    city: 'East Village, NYC', region: 'Americas',
    blurb: 'A foster-based, strictly no-kill rescue in the East Village that takes abandoned animals from kill shelters into safe homes, matching each one with the right family.',
    website: 'https://socialteesnyc.org/see-our-animals',
    // Source of truth: https://raw.githubusercontent.com/ZacSweers/socialteesjs/main/data/pets.json
    // (referenced from socialteesnyc.org's Petfinder widget config).
    dogs: [
      { id: 'st-tink', name: 'Tink', breed: 'Pit Bull Terrier / Boston Terrier', age: '6 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1306832174', bio: 'Don\'t sleep on this Tiny girl. When we say pocket pit - we mean it. If you know anything about pits - they are all solid so 34lbs of pit is very very small. More than that she\'s perfect - she walks around like she\'s never had a bad day in her life.' },
      { id: 'st-leverne-and-shirely', name: 'Leverne & Shirely', breed: 'Chihuahua', age: '8 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1305760237', bio: 'BONDED PAIR - Daughter and Mother - Thier owner was found dead Shirley - 8 years & 7lbs, Chi Mix, Spayed & Laverne - 12 years & 8lbs, Chi Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-millie', name: 'Millie', breed: 'Jack Russell Terrier / Chihuahua', age: '5 mo', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1305760228', bio: 'Millie - 5 months & 10lbs (as of 5/12), Chi Mix, Spayed *expected full grown size about 20lbs. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-dandelion', name: 'Dandelion', breed: 'Dachshund / Chihuahua', age: '5 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1305538026', bio: 'Dandelion - 5 years & 15lbs, Dachshund Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-marty', name: 'Marty', breed: 'Jack Russell Terrier / Jack Russell Terrier', age: '2 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1305538017', bio: 'Marty - 2 years & 13lbs, Terrier Mix, Neutered. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-gidget', name: 'Gidget', breed: 'Chihuahua', age: '2 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1305537981', bio: 'Gidget - 2 years & 9lbs, Chi Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-november', name: 'November', breed: 'Husky', age: '9 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1304247374', bio: 'November - 9 years, 49lbs, Husky Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-cash', name: 'Cash', breed: 'Australian Shepherd', age: '10 mo', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1304247365', bio: 'Cash - 10 months, 43lbs, Aussie Mix, Neutered Expected around 45lbs full grown. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-aubrey', name: 'Aubrey', breed: 'Basenji / Jack Russell Terrier', age: '4 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1304247350', bio: 'Aubrey - 4 years, 26lbs, Basenji/Terrier Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-cooper', name: 'Cooper', breed: 'Golden Retriever / Australian Shepherd', age: '3 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1304247341', bio: 'Cooper - 3 years, 46lbs, Retriever/Aussie Mix, Neutered. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-daisy', name: 'Daisy', breed: 'Beagle / Jack Russell Terrier', age: '2 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1304247313', bio: 'Daisy - 2 years, 34lbsm Beagle/Terrier Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-fuzzy', name: 'Fuzzy', breed: 'Beagle / Labrador Retriever', age: '1 yr', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1304247288', bio: 'Fuzzy - 1 year, 32lbs, Beagle/Lab Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-coral', name: 'Coral', breed: 'Cattle Dog / Australian Shepherd', age: '2 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1303753683', bio: 'Coral - 2 years, 59lbs, Heeler Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-tucker', name: 'Tucker', breed: 'Great Pyrenees / Labrador Retriever', age: '9 mo', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1302121950', bio: 'Tucker - 9 months, 58lbs, Pyr & Lab Mix, Neutered Estimated Full Grown Size Around 80lbs. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-cecillia', name: 'Cecillia', breed: 'Dachshund / Chihuahua', age: '2 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1301146112', bio: 'This pup was rescued from a hoarding situation in PR - involving about 40 dogs. Due to this these pups are on the shyer side and need patient people who will give them time to get used to normal life. They are very sweet dogs: just need more time and patience.' },
      { id: 'st-carolina', name: 'Carolina', breed: 'Dachshund / Chihuahua', age: '2 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1300678089', bio: 'Carolina - 2 year & 13lbs, Chi Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-shyla', name: 'Shyla', breed: 'Collie / Beagle', age: 'Puppy', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057653', bio: 'Shyla is truly the sweetest, happiest little soul and has been such a joy to foster. She’s incredibly friendly and full of life—always ready to play, especially if there’s a squeaky toy, a ball, or her favorite Kong involved.' },
      { id: 'st-euphoria', name: 'Euphoria', breed: 'Boxer', age: '5 mo', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057643', bio: 'Euphoria is an incredibly lucky parvo survivor! No long term health implications just bragging rights!' },
      { id: 'st-bitzi', name: 'Bitzi', breed: 'Husky / Labrador Retriever', age: '5 mo', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057554', bio: 'Bitzi - 5 months & 25lbs (as of 4/14), Husky Mix, Spayed Expected Full Grown Size Around 50lbs. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-carissa', name: 'Carissa', breed: 'Chihuahua / Dachshund', age: '5 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057528', bio: 'This pup was rescued from a hoarding situation in PR - involving about 40 dogs. Due to this these pups are on the shyer side and need patient people who will give them time to get used to normal life. They are very sweet dogs: they just need more time and patience.' },
      { id: 'st-callie', name: 'Callie', breed: 'Chihuahua / Dachshund', age: '1 yr', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057519', bio: 'This pup was rescued from a hoarding situation in PR - involving about 40 dogs. Due to this these pups are on the shyer side and need patient people who will give them time to get used to normal life. They are very sweet dogs: just need more time and patience.' },
      { id: 'st-cosmo', name: 'Cosmo', breed: 'Chihuahua / Dachshund', age: '2 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057449', bio: 'Cosmo - 2 years & 16lbs, Chi Mix, Neutered. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-columbus', name: 'Columbus', breed: 'Chihuahua / Dachshund', age: '2 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1299057398', bio: 'Columbus needs a special adopter because he\'s mostly blind due to cataracts in his eyes. We\'re hoping there is someone out there that is wanting to adopt him and possibly do this surgery for him. This pup was rescued from a hoarding situation in PR - involving about 40 dogs.' },
      { id: 'st-snug', name: 'Snug', breed: 'Beagle / Blue Heeler', age: '4 mo', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1297038423', bio: 'Snug - 4 months & 10lbs (as of 3/10), Heeler/Beagle Mix, Spayed Estimated around 25bs full grown. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-fern', name: 'Fern', breed: 'Chihuahua / Jack Russell Terrier', age: '9 mo', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1301223015', bio: 'Fern is a sweet, snuggly little girl who believes life is best lived as close to her humans as physically possible. With her low-to-medium energy, she’s happy to play during the day, but her true talent is expert-level cuddling, preferably right on top of you.' },
      { id: 'st-fifi', name: 'Fifi', breed: 'Chihuahua / Jack Russell Terrier', age: '4 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1293021915', bio: 'FIFI is a happy, confident little girl with a heart full of love and a playful spirit to match. She greets you with the sweetest excitement, her tail wagging nonstop the moment she sees you, and her favorite place in the world is cuddled up right next to you (or right on top of y…' },
      { id: 'st-nathaniel', name: 'Nathaniel', breed: 'Beagle', age: '7 mo', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1292900985', bio: 'Nathaniel - 7 months & 20 lbs (as of 4/18), Beagle/Spaniel Mix, Neutered Estimated around 30lbs full grown. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-gregory', name: 'Gregory', breed: 'Beagle / Jack Russell Terrier', age: 'Puppy', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1292900949', bio: 'Gregory - 13 weeks & 9lbs (as of 4/17), Beagle/Terrier Mix, Neutered Estimated around 30lbs full grown. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-cornelius', name: 'Cornelius', breed: 'Cattle Dog / Australian Shepherd', age: '10 mo', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1291189856', bio: 'Cornelius was clearly severly mistreaed in his past life as he has some old injuries as does his mom. As a result he has a limp and takes a daily anti-inflamatory. His future parents might have to consider surgery down the line once he\'s fully done growing.' },
      { id: 'st-baby', name: 'Baby', breed: 'Labrador Retriever', age: '8 mo', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1290497247', bio: 'We aren\'t exactly sure of her breed - she was rescued from Kosovo. She has this amazing soft fur - right now she\'s shaved down but she\'s actually got double coated fur.' },
      { id: 'st-loki', name: 'Loki', breed: 'Pug / Beagle', age: '3 yrs', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1289256308', bio: 'Loki is sweeter than honey with the gentlest soul and so much love to give. He is a timid and shy boy, but in spite of whatever circumstances he\'s been through, he is still immediately affectionate and learns to trust quickly.' },
      { id: 'st-leo', name: 'Leo', breed: 'Husky', age: '2 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1289025647', bio: 'Leo has been doing so well now that we are in a routine. He is so cuddly and sweet and will play with a toy to entertain himself or have a nice long nap as long as he gets a long walk (30-45 min) in the AM, a quick mid-day walk, and night time walk.' },
      { id: 'st-hank', name: 'Hank', breed: 'Labrador Retriever / Basset Hound', age: '2 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1287513031', bio: 'Hank - 2 years, 62lbs, Basset Mix, Neutered. In foster care with Social Tees, ready for the right home.' },
      { id: 'st-hazel', name: 'Hazel', breed: 'Beagle / Australian Shepherd', age: '5 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1284551006', bio: 'Hazel is a gem of a dog. She would do best in a home in the calmer parts of the city or beyond aka the burbs.' },
      { id: 'st-currant', name: 'Currant', breed: 'Chihuahua / Jack Russell Terrier', age: '15 yrs', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1257036548', bio: 'Currant needs a home in the burbs, she prefers the calm life over the city life.' },
      { id: 'st-ted', name: 'Ted', breed: 'Pug / Jack Russell Terrier', age: '6 yrs', sex: 'Male', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1217734917', bio: 'Ted is a very special boy with Pulmonary Hypertension - please read below for more info' },
      { id: 'st-shiloh', name: 'Shiloh', breed: 'Beagle', age: '1 yr', sex: 'Female', photo: 'https://media.adoptapet.com/image/upload/if_fc_gt_0,c_fill,g_face,h_600,w_800/if_else/c_fill,g_auto:classic,h_600,w_800/if_end/f_auto,q_auto/1163925219', bio: '1 year, 25lbs, Beagle Mix, Spayed. In foster care with Social Tees, ready for the right home.' },
    ],
  },
  {
    id: 'animal-haven', order: 5,
    name: 'Animal Haven',
    city: 'Manhattan, NYC', region: 'Americas',
    blurb: 'Serving New York City since 1967 with top-quality care, behavior support and enrichment for abandoned cats and dogs across the Tri-State area.',
    website: 'https://animalhaven.org/adopt/dogs',
    dogs: [
      { id: 'ah-junior', name: 'Junior', breed: 'Rescue dog', age: '5 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/fe61fa233f311fb2e10df772528a6b5f/e0cd29f27c809591de362caf81873758.jpg', bio: 'Junior is in Animal Haven\'s care, ready to find his forever home.' },
      { id: 'ah-mario', name: 'Mario', breed: 'Rescue dog', age: '3 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/869f57a4ce3d69d6d2b689a00fa3993f/3bcea9e6a7dc8d0589032b53272191a6.jpg', bio: 'Mario was found as a stray on the streets of NYC. This terrified boy was trembling when he was caught by police who brought him to a municipal shelter. It\'s hard to say what his life was before he was found, but he\'s clearly been through a lot.' },
      { id: 'ah-ryan', name: 'Ryan', breed: 'Rescue dog', age: '7 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/04c0cc176d47da2a89934b9d13842e1d/d3b466234232bfd5d58d7bd7f3f84f11.jpg', bio: 'Ryan found his way to Animal Haven when his previous owner sadly did not have enough time to take care of him. Surrenders are always difficult for pets, but Ryan has taken things in stride and is settled in here.' },
      { id: 'ah-buddy', name: 'Buddy', breed: 'Rescue dog', age: '5 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/a743871abc28eeb47c19d44eb244e423/f9dcc0ba98f07b144747bee7e109a492.jpg', bio: 'Meet Buddy! This affectionate hound mix went into foster care under difficult circumstances when his owner sadly fell terminally ill. Buddy is looking for a home that will cherish him just as much as they did, and whoever finds him will be very lucky indeed.' },
      { id: 'ah-henrietta', name: 'Henrietta', breed: 'Senior', age: '16 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/ca4f7b46eff805b6bb308f519942f85a/423dade9429c408a813c255903fac210.jpeg', bio: 'Henrietta is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-quinn', name: 'Quinn', breed: 'Puppy', age: '2 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/c64a3de7e62bc3e55fb62149725e096e/23f8c62e8a9e042e8a05528925db1c37.jpg', bio: 'Quinn is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-pixel', name: 'Pixel', breed: 'Puppy', age: '3 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/f918a188c064107bef34849bd742771b/0543e55b28c612cb3d298a77be7864d6.jpg', bio: 'Pixel is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-gina', name: 'Gina', breed: 'Rescue dog', age: '3 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/0e368c36f307d5898275dcea4438bbaa/b705f8040ad44ad758653214a0af7b0a.jpeg', bio: 'Gina is a sweet and high energy girl looking for an active and engaged home ready for a spunky dog like her! Gina is an Underdog who has been shining in our rehabilitative program, and does well when she has structure to keep her both mentally and physically occupied!' },
      { id: 'ah-marcia', name: 'Marcia', breed: 'Rescue dog', age: '1 yr', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/6d99fd93a8542ca16d0cf30e6f3a497a/0a63c68292bc9103202c5222036e9c25.jpg', bio: 'Marcia deserves to pat herself on the back—raising SIX puppies is no small feat! Marcia arrived at Animal Haven with her nursing puppies, and has been an all-star mom during her time here. Her pups are now all grown up and ready to find homes of their own.' },
      { id: 'ah-alvin', name: 'Alvin', breed: 'Rescue dog', age: '2 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/44050d8d3e75c86275d2ecb68072d183/9c7b574b57013ff42b960d766a2c178b.jpg', bio: 'If you’re looking for a sweet, mellow companion, Alvin might be the guy for you! Alvin is a bit shy around new people, but once he learns you’re no threat, he’ll offer you a small tail wag.' },
      { id: 'ah-wiggly-diggly', name: 'Wiggly Diggly', breed: 'Senior', age: '14 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/9ea04b5122ba2540b9c9e34c73f52b5d/9b1ac0de4ef8ff0a368b649482b61fd2.jpg', bio: 'Wiggly Diggly is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-samsung', name: 'Samsung', breed: 'Puppy', age: '3 mo', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/fb43d9086f2d1e68786bd51e54543860/c609894a228cdb8def9211c51eaff629.jpg', bio: 'Samsung is in Animal Haven\'s care, ready to find his forever home.' },
      { id: 'ah-nokia', name: 'Nokia', breed: 'Puppy', age: '3 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/336843686bbff7a2879393c2ef25cace/8059345b82d3a3072e2db55236d2a7f7.jpg', bio: 'Nokia is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-lana', name: 'Lana', breed: 'Rescue dog', age: '1 yr', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/c3cbcfeb19483daec913dfdf8d454f4b/e14094988f506883693144b09161f3cd.jpeg', bio: 'Lana is a sweet soul who wears her heart on her sleeve, and she wouldn\'t have it any other way! She lights up when meeting new people and is big on snuggles. Shelters are often a challenging environment for dogs, and they each handle it a little bit differently.' },
      { id: 'ah-darcy', name: 'Darcy', breed: 'Puppy', age: '2 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/ad2a9e6d6516ec881f696ba41773f9f0/eb1765b94ad08b2324b8f58598ad653e.jpg', bio: 'Our “D” puppies arrived with their mama Della, and ohmygoodness are they cute and chunky! These puppies are roly poly little things and are probably going to grow up to be on the larger size.' },
      { id: 'ah-gazpacho', name: 'Gazpacho', breed: 'Young', age: '8 mo', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/0466e97ecc939b20d06e526ab9f8e40c/75a8cdf0be02d329a9c97d485674e1f9.jpg', bio: 'Gazpacho and his pals came from a local home that became overwhelmed when their male and female dog had back-to-back litters of puppies. In all, we believe that there were nearly 20 dogs living in this home.' },
      { id: 'ah-blackberry', name: 'Blackberry', breed: 'Puppy', age: '3 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/74da31aad05e0e0703a23e2159b6a159/aa0d7529d6d40db727448c0cae8df1dd.jpg', bio: 'Blackberry is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-coco', name: 'Coco', breed: 'Puppy', age: '2 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/b48e05664b4adfb30bad779fa522283f/d9cdbc91874170919b27d1f5c79998c4.jpg', bio: 'Coco is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-motorola', name: 'Motorola', breed: 'Puppy', age: '3 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/000142a438395467da1683ed3508de1c/afd8261b76214bb4792824a9001461ce.jpg', bio: 'Motorola is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-monte', name: 'Monte', breed: 'Rescue dog', age: '7 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/c645f0f9f29397f1dfb7801fb3e26fd2/20240209101356.png', bio: 'Monte lives with a condition called Megaesophagus. This condition varies in severity on a case by case basis with all dogs and we look to our vets directly on recommendations for his care.' },
      { id: 'ah-della', name: 'Della', breed: 'Rescue dog', age: '2 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/e76769b1c392a769f0edcb3d61b0de40/b49f4304e9c88638c8a4ba21c6140107.jpg', bio: 'Meet Della! This darling mama has been lovingly raising her puppies—and she’s doing an amazing job (they’re nice and chunky)! Della is almost free from mom duty, but we’re showing her to prospective adopters.' },
      { id: 'ah-jack', name: 'Jack', breed: 'Rescue dog', age: '2 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/b9a4011a8559beea95e8ecb26fe59763/43ad2974bb83096316448ff2a268198c.jpeg', bio: 'Jack was rescued from the side of a road in St. Lucia, where he was found limping badly. He was scooped up and brought to the safety of HelpAWS’ sanctuary, where he received initial care.' },
      { id: 'ah-sailor-mercury', name: 'Sailor Mercury', breed: 'Rescue dog', age: '2 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/45b2f4001939578f8407cdf0a188cdc0/3fb3080e76be8ed5ca8e08cf489d240e.jpg', bio: 'Sailor Mercury is a sweet soul who needs a hand with building her confidence! Sailor Mercury first arrived at Animal Haven as a puppy in late 2024. She was adopted and then returned due to no fault of her own.' },
      { id: 'ah-daria', name: 'Daria', breed: 'Rescue dog', age: '5 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/54f19a4f0579540d99408ccebeccde07/c22b7f572a8033110f0e0c9fbee285c1.jpeg', bio: 'Meet the smiliest girl around, Daria! This pocket pibble was rescued from an overcrowded shelter in Louisiana, and has been getting used to big city life.' },
      { id: 'ah-egg-drop-soup', name: 'Egg Drop Soup', breed: 'Rescue dog', age: '1 yr', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/7c0b9d02a48152b547e5e49966a8d038/6b2a091deec43f855c3ba9d8a6949218.jpg', bio: 'Egg Drop Soup and her pals came from a local home that became overwhelmed when their male and female dog had back-to-back litters of puppies. In all, we believe that there were nearly 20 dogs living in this home.' },
      { id: 'ah-lady', name: 'Lady', breed: 'Rescue dog', age: '5 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/9aa1299872b307a4f651d76dd7a421f6/a6547a0ab478c4e74990aa6a2a5c43cc.jpg', bio: 'Lady is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-timberlake', name: 'Timberlake', breed: 'Young', age: '10 mo', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/289d6892eda70a759825cd5431875e4c/cc87c43dc92316cff29a4baecd3d293f.jpg', bio: 'Meet Timberlake! This goofy pup is cute and eager to please. And that’s a good thing, because we’ll be honest: Timberlake is a little bit of a project (but one with a TON of potential—and we’re here to help you every step of the way).' },
      { id: 'ah-lottie', name: 'Lottie', breed: 'Rescue dog', age: '9 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/6b3cd6a7deac2006b1c708ec4ac84444/2d6495acf0c6ad00182dc2529d692204.jpg', bio: 'Watch out, world! Lottie is HERE! This spunky senior girl has been through quite a lot lately. She was found running loose in a trailer park in New Jersey. Thankfully, a Good Samaritan spotted her and brought her to a local municipal shelter.' },
      { id: 'ah-douglas', name: 'Douglas', breed: 'Rescue dog', age: '6 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/8911f33b7ed2ab9ec13fe7a11840d536/0c14842853b4a0bd9c7e272ffb4a25f7.jpg', bio: 'Poor Douglas was found on the side of a road in Antigua, dragging his hind legs. Although his rescuers initially thought he had been hit by a car, upon further inspection his injuries were actually fairly old.' },
      { id: 'ah-eli', name: 'Eli', breed: 'Rescue dog', age: '2 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/7641e9c6a5e869cf6cfe1b3f26264c65/7209ccdb27a90a7c2a9abb38a94c8c0d.jpg', bio: 'Eli is in Animal Haven\'s care, ready to find his forever home.' },
      { id: 'ah-spunky', name: 'Spunky', breed: 'Rescue dog', age: '3 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/bd3084d4bf5cac15bfc926dbf6ff8d86/cca93a9ea9536b1ad692cbe86bd2e71d.jpg', bio: 'Spunky is ready to hop right into your life! Honestly, his name says it all. This guy is super spunky, peppy, and sweet. He is an energetic guy and will thrive with an active family! Adopt Spunky!' },
      { id: 'ah-debbie', name: 'Debbie', breed: 'Puppy', age: '2 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/7ddcc803f1d5db0071bbe631074a120c/5459c7145f999df144ab8f89f1008fdd.jpg', bio: 'Our “D” puppies arrived with their mama Della, and ohmygoodness are they cute and chunky! These puppies are roly poly little things and are probably going to grow up to be on the larger size.' },
      { id: 'ah-vera', name: 'Vera', breed: 'Puppy', age: '2 mo', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/e796aaefde0b01541f7d6579846e62b9/e7639ebdf32baa3cef305760621da856.jpg', bio: 'Vera is in Animal Haven\'s care, ready to find her forever home.' },
      { id: 'ah-alabaster', name: 'Alabaster Snowball', breed: 'Rescue dog', age: '2 yrs', sex: 'Male', photo: 'https://new-s3.shelterluv.com/profile-pictures/073245aea22028521d02f8adc2e3d354/0746a8838689689824ec33a6890b7299.jpg', bio: 'We know what you’re thinking: Alabaster Snowball is CUTE! And you are right—this energetic pup is adorable, from his fluffy ears to his waggy tail. Beneath all that cuteness, though, is a really anxious guy.' },
      { id: 'ah-tuna', name: 'Tuna', breed: 'Rescue dog', age: '8 yrs', sex: 'Female', photo: 'https://new-s3.shelterluv.com/profile-pictures/078f1c06a61a1e19b959625934e11ec7/e9c4c7b252a0a702826bc5690f6dce5d.jpg', bio: 'We are SMITTEN with Tuna! This darling girl was recently surrendered and is adjusting to her life at Animal Haven. We’ve been giving her lots of love as she settles in. Tuna is an absolutely lovely pup and is looking for a home that will cherish her as much as we do. Adopt Tuna!' },
    ],
  },
];

async function main() {
  const links = [];
  for (const s of SHELTERS) {
    await db.collection('shelters').doc(s.id).set({ ...s, updatedAt: FieldValue.serverTimestamp() }, { merge: true });
    // Generate (or rotate) the shelter's private edit token + shareable link.
    const token = randomUUID().replace(/-/g, '');
    await db.collection('shelter_secrets').doc(s.id).set({ token, updatedAt: FieldValue.serverTimestamp() }, { merge: true });
    const link = `${BASE}/shelter/${s.id}?t=${token}`;
    links.push({ name: s.name, link });
    console.log(`  · ${s.name} (${s.dogs.length} dogs)`);
  }
  console.log(`\nDone. ${SHELTERS.length} shelters written.\n`);
  console.log('================  EDIT LINKS — give one to each shelter  ================');
  for (const l of links) {
    console.log(`\n${l.name}:\n${l.link}`);
  }
  console.log('\n=========================================================================');
  console.log('Each shelter can edit ONLY their own profile + dogs from their link.');
  console.log('Re-run this script to rotate tokens (old links stop working).');
}

main().catch((err) => { console.error('import_shelters failed:', err); process.exit(1); });
